<<<<<<< HEAD
StringLiterals:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 200

AllCops:
  Exclude:
    - db/schema.rb
